### PR TITLE
Dockerized

### PR DESCRIPTION
**Pull request by ffaraji**
Inside the docker folder, scripts are developed in order to run the server inside a docker container.
Please review and test it and if you agree with these changes, we can merge it to master.

Here is guid to run:
Inside the docker folder:
1. run ./build.sh 
2. run ./start.sh <map name> (./start.sh kobe) ; run normal simulation
3. run ./precompute.sh <map name> ; run in precomute mode

log folder shared with the container, so you can see the server logs there.
maps folder shared with the container so server loads maps from this folder.

### CODE REVIEW

**Comment by modaresimr** [comment]
I suggest to have a command like `rcrs` and we can then do several actions. instead of having one file for everything.
In future we will include scenario editor and more on.
therefore, we can have a script named `rcrs-docker.sh` the command can be 

```rcrs-docker.sh start```
```rcrs-docker.sh start -m kobe```
```rcrs-docker.sh precompute``` 
```rcrs-docker.sh scenario-editor```

# inside rcrs-docker.sh
```
docker run -it ..... rcrs $*
```
I understand your concern about new comers, so we can add help in the begning of the script if there is no argument

# inside the script for the docker
we need to handle several inputs



# the tmp file is anti-pattern
solutions:
## using external repository
it is similar to what is already done in https://github.com/roborescue/rcrs-docker

## put Dockerfile in the root directory 
you can use the `rcrs-docker.sh` in the `script` folder.

**Comment by ffaraji** [comment]
We discussed using an external repository in the meeting.
The problem with the external repository is that developers will not be able to run their own modified server or a special branch of repository. 
That is why I put the docker file inside the server instead of a separate repository.

**Comment by modaresimr** [comment]
> We discussed using an external repository in the meeting. The problem with the external repository is that developers will not be able to run their own modified server or a special branch of repository. That is why I put the docker file inside the server instead of a separate repository.

I understand this point of view. 
I have seen many big projects use external docker repository. I have also seen projects that use Docker file inside the repository. 

However, for your approach, please take a look at one similar example:
https://github.com/NginxProxyManager/nginx-proxy-manager/tree/develop/docker
They use a docker folder inside the project, then, they use a docker-compose file for development and mount the root directory in the development (you can use it with docker run too)

**Review by gnardin — CHANGES_REQUESTED** [review]
Dear @ffaraji

I have few comments:

1. Move the `docker` folder into the `scripts` folder
2. I tried running the `./build.sh` inside the `docker` folder and I receive the following error messages:
```
cp: cannot copy a directory, '../docker', into itself, './tmp/docker'
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /var/lib/snapd/void/Dockerfile: no such file or directory
```
3. You should add a `README` file inside the `docker` folder to instruct the user how to use the scripts because I supposed I should run the `build.sh` first, but I am not 100% sure I am right.

Thanks,
@gnardin

**Pull request closed without merging**
