### PR TITLE
Fix log viewer

### PR DESCRIPTION
**Pull request by harrki**
Hello, I'm Haruki Uehara from AIT.
I fixed the problem of images not loading correctly when playing logs, the problem of sometimes failing when playing 7z logs, and the problem of missing config files required for playing logs.
As for the problem that the image did not load correctly, the path of the image was wrong and I fixed it.
As for the problem that sometimes fails when playing 7z logs, there was a problem with the external library used, so I upgraded the library and fixed it.
I added the necessary config files for the problem of not including the config files to play the logs.

### CODE REVIEW

**Comment by gnardin** [comment]
Dear @harrki 
Thank you for your effort in fixing the inconsistencies in the LogViewer.
@modaresimr and @gnardin were requested to review the PR. But I can tell you in advance that creating the config files under `config` instead of the `<MAP>/config` is something that requires further thought to avoid duplication of information.
Kind regards,

**Comment by harrki** [comment]
Dear @gnardin

Thank you for your quick response. I also acknowledge the need to avoid duplication of information.
However, the present logviewer does not work with the default maps included in the server.
So I will add a commit that adds the configuration necessary to play the log to logviewer.cfg in `<MAP>/config`.

Kind regards,

**Review by gnardin — APPROVED** [review]
These changes take into account the previous suggestion of not creating a `config` sub-directory under the root `rcrs-server` folder.

**Comment by gnardin** [comment]
@harrki Your PR has been merged. Thank you,

**Pull request merged**
