### PR TITLE
 WIP: Add ViewerEventLogger

### PR DESCRIPTION
**Pull request by armanaxh**
We need a kernel side event logger for the web viewer. We will use these logs on the Webviewer.

P.S. I had a conflict with master, and I solved it!

### CODE REVIEW

**Comment by gnardin** [comment]
The enhancement requires the `org.json.JSON` library whose dependency was included in the `build.gradle` file. Some changes were also made in the `.gitignore` to ignore the log files generated by this enhancement.

**Comment by modaresimr** [comment]
Great job. Just some suggestion:
Suggestion 1:
In toJson method we can obey the class inheritance. For example, there is no need to repeat the same lines in every class.

Example in Building.java
```     
    public JSONObject toJson(){
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("Id", this.getID());
        jsonObject.put("EntityName", this.getEntityName());
        jsonObject.put("Brokenness", this.getBrokenness());
        jsonObject.put("Fieryness", this.getFieryness());
        jsonObject.put("Floors", this.getFloors());

        JSONArray edgesJson = new JSONArray();
        for (Edge edge: this.getEdges()){
            edgesJson.put(edge.toJson());
        }
        jsonObject.put("Edges", edgesJson);

```
### this code could be changed to 

StandardEntitiy.java
```
    public JSONObject toJson(){
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("Id", this.getID());
        jsonObject.put("EntityName", this.getEntityName());
        return jsonObject
```
Area.java
```
    public JSONObject toJson(){
        jsonObject =super.toJson()
        JSONArray edgesJson = new JSONArray();
        for (Edge edge: this.getEdges()){
            edgesJson.put(edge.toJson());
        }
        jsonObject.put("Edges", edgesJson);
        return jsonObject
```
Building.java
```
    public JSONObject toJson(){
        jsonObject =super.toJson()
        jsonObject.put("Brokenness", this.getBrokenness());
        jsonObject.put("Fieryness", this.getFieryness());
        jsonObject.put("Floors", this.getFloors());
        return jsonObject
```

Please note that these codes may raise exceptions. It is better to change this to
```
        jsonObject =super.toJson()
        jsonObject.put("Brokenness", this.isBrokennesDefined()?this.getBrokenness():JSONObject.NULL);
        jsonObject.put("Fieryness", this.isFierynessDefined()?this.getFieryness():JSONObject.NULL);
        jsonObject.put("Floors", this.isFloorsDefined()?this.getFloors():JSONObject.NULL);
```

**Comment by modaresimr** [comment]
Suggestion 2:
instead of String "Floors" (an example) use constants that are defined for example StandardPropertyURN.FLOORS
It makes the code to be more consistent.

**Comment by modaresimr** [comment]
Suggestion 3:
In the EventLogger, I suggest sending only the changeset instead of the whole entity (even with the filtered function which is not a good idea since it makes it hard for future changes) 
You can easily add toJson the changeset (I recommend this) or use sth like bellow:
```
@Override
    protected void handleTimestep(final KVTimestep kvt) {
        super.handleTimestep(kvt);

        JSONArray jsonEntities = new JSONArray();
        for (EntityID id : kvt.getChangeSet().getChangedEntities()) {
            Entity entity = model.getEntity(id);
            changedProperties=kvt.getChangeSet().getChangedProperties(entity);
            JSONObject jsonEntity =new JSONObject();
            jsonEntity.put(ID,entity.id);
            for each p in changedProperties:
                    jsonEntity.put(p,p.value())//it should be consistent (particularly with toJson)

            jsonEntities.put(jsonEntity);
        }

        JSONObject jsonRecord = new JSONObject();

        jsonRecord.put("changeset", jsonEntities);
        jsonRecord.put("TimeStep", kvt.getTime());

        writeJsonFile(jsonRecord, logFilePath, true);
    }
```

**Comment by modaresimr** [comment]
Suggestion 4:
Don't think about the length of the standardURN it is easily coded as a small object with any compression algorithms. The consistency of the code is more important than any other thing. You can let the webserver compress it or even you can compress and decompress on the fly.

For the moment I suggest not thinking about compression but maybe you can think about http://techslides.com/extract-zip-and-rar-files-with-html5.

**Comment by armanaxh** [comment]
Thanks so much for the review.
I apply these changes and create new PR. You can track the changes in `viewer-event-logger ` branch. [here](https://github.com/roborescue/rcrs-server/tree/viewer-event-logger).

Can you please explain more about `Suggestion 3` ?! Can I get only changed properties of `ChangeSet` entities?

**Comment by modaresimr** [comment]
It is an example code but if you add a toJson method in changeset you can find all the details :)
```
JSONArray jsonEntities = new JSONArray();
        for (EntityID id : kvt.getChangeSet().getChangedEntities()) {
            Entity entity = model.getEntity(id);
            changedProperties=kvt.getChangeSet().getChangedProperties(entity);
            JSONObject jsonEntity =new JSONObject();
            jsonEntity.put(ID,entity.id);
            for each p in changedProperties:
                    jsonEntity.put(p,p.value())//it should be consistent (particularly with toJson)

            jsonEntities.put(jsonEntity);
        }
```

**Comment by modaresimr** [comment]
I have another suggestion :D
We can have one JSON file for each timestep and so we can add live streaming capability easily since any new timestep can easily get from web-server. 

I also suggest recording all the world model in temporary storage  for fast access in the web viewer
Do you have any estimate on the storage needed for saving the JSON file?

**Comment by modaresimr** [comment]
Suggestion
For WebGL, I also suggest to see similar materials 
here is an example of WebGL with 40000 objects and framerate of 60fps https://webglsamples.org/google-io/2011/index.html   
Also I recommend using similar opensource material such as [tangram](https://github.com/tangrams/tangram)
[Example 1](http://tangrams.github.io/gui-demo/) [example2](https://github.com/tangrams/tangram-sandbox) [example 3](https://github.com/tangrams/super-map-ball)

Please think 3D (with the possibility to have a 2D model) in the created WebViewer ;)
Another note please move the json logger into the Kernel

**Comment by modaresimr** [comment]
Suggestion number? :D
Please take a look at FileLogWriter,  class in rescuecore2, and how it is used in Kernel.
I think it would be easier and robust if you can implement the JSON logger in such away.
Please note that in the Viewer it is important to extract all the possible information. For example, the perception of each agent, the command sent by each agent, and the messages received. 
Please find the following lines in Kernel.java
```
                log.writeRecord(new StartLogRecord());
                log.writeRecord(new InitialConditionsRecord(worldModel));
                log.writeRecord(new ConfigRecord(config));
                //for each timestep:
                     log.writeRecord(new UpdatesRecord(time, changes));
                        //for each id in agents:
                             log.writeRecord(new PerceptionRecord(time, id, visible, heard));
                log.writeRecord(new EndLogRecord());
```

**Comment by armanaxh** [comment]
> I have another suggestion :D
> We can have one JSON file for each timestep and so we can add live streaming capability easily since any new timestep can easily get from web-server.
> 
> I also suggest recording all the world model in temporary storage for fast access in the web viewer
> Do you have any estimate on the storage needed for saving the JSON file?

We have a separate Json for each TimeStep. can see an 
JsonLog example in [here](https://github.com/roborescue/rcrs-server/blob/master/boot/records/test__1598630733534_viewer_event_log.jlog). Is that what did you mean?
(in cycle 0 we send the whole map) 

And if you want to know the log file size. For example, now:
VC (369 cycles): 14MB
Istanbul (215 cycles): 9.4MB
Test (100 cycles): 173KB

It has improved a bit in the new changes. And in compression, it is almost 5 (or 10) times less than the original JsonLog.

**Comment by armanaxh** [comment]
> I have another suggestion :D
> We can have one JSON file for each timestep and so we can add live streaming capability easily since any new timestep can easily get from web-server.
> 
> I also suggest recording all the world model in temporary storage for fast access in the web viewer
> Do you have any estimate on the storage needed for saving the JSON file?

In fact, we do not think about steaming at the moment. We prepare more for online competition, in which case streaming creates unnecessary complexity. And now we want to serve the whole file.

And if you want the file size. For example, now:
VC (369 cycles): 14MB
Istanbul (215 cycles): 9.4MB
Test (100 cycles): 173KB

It has improved a bit in the new changes. And in compression, it is almost 5 (or 10) times less than the original LogFile.

**Comment by modaresimr** [comment]
I mean that for each map we create a folder (i.e. testrun) which contains the following files:
- testrun/summary.jlog
- testrun/cycle0.jlog
- testrun/cycle1.jlog
- ...
- testrun/cycle300.jlog

In each cycle (cycle i.jlog) the following property may exist:
- Info {cycle, score, status (i.e. start or end), datetime ....} (all cycles)
- Entities  (initial cycle ) 
- ConfigRecord (initial cycle) 
- Prefix{  //(initial cycle)
-- entity_urn: "urn:rescuecore2.standard:entity: ",
-- property_urn="urn:rescuecore2.standard:property:"
-- message_urn="urn:rescuecore2.standard:message:"}
- Commands (all cycles except 0)
- UpdatesRecord (all cycles except 0)
- PerceptionRecord (cycles except 0)
- Status: {start/end} (i.e. End cycle)
- ConnectedComponents (Agents, Simulators, Viewers) (Initial Cycle)



in summary.jlog the following property may exist
- team name
- map name
- run start time
- run end time
- total cycle
- last cycle info {time, score, status (i.e. start or end) ....}
 
The prefix property allows you to easily remove all prefix for having smaller files (If you want smaller file but I think it is better to not think about it now)

For live web viewer following process will happen: It is so similar to having all timesteps in one file.
```
cycle=0 
function getCycles(){
         $.getJSON("cycle"+cycle+".jlog")
               .done(function(data) {
                          if (data.status!="end"){ 
                              cycle++; 
                              getCycles();
                          }
                          //process(data)
                }).fail(function(data){
                          setTimeout(getCycles, 1000);
                })
}
$.getJSON("summary.jlog")
     .done(function(data){
                      getCycle();
                       //process(data)
      });
```

**Pull request merged**
